### ISSUE TITLE
Homework Tracker

### ISSUE THREAD

**Issue by Maxruiz710** [Maxruiz710/SSW-345#1]
- [x] Upload github profile picture
- [x] Setup Project Teams
- [ ] Form Groups and Describe Project
- [ ] Class Modeling
